
- name: Query the hostname
  hosts: all
  tasks:
    - command: cat /etc/hostname
      register: hostname
      changed_when: False

- name: Install the Bitflow data collector and injector
  hosts:
    - hypervisors
    - vms
  tags: [ collector, injector ]
  vars:
    injector: "{{ injector_general }}"
  tasks:
    - include_tasks: ../../Common/Ansible/bootstrap-docker-tasks.yml
      become: true
    - include_tasks: ../../Common/Ansible/bitflow-collector-tasks.yml
      become: true
    - include_tasks: ../../Common/Ansible/injector-tasks.yml
      become: true
