#!/usr/bin/env ansible-playbook

- name: Check data collector output
  hosts: zerops-collector
  tasks:
    - include_role:
        name: ../../roles/zerops-collector
        tasks_from: check-data-directory

- name: Check sipp data output
  hosts: sippstress
  vars:
    output_check_directory: "{{ sipp.load_log_dir }}"
    max_file_age_seconds: 300
  tasks:
    - include_tasks: ../../ansible-common/check-output-directory.yml
