#!/usr/bin/env ansible-playbook



- name: Launch a compute instance
  hosts: localhost
  vars_files: "{{ myvarfile }}"
  remote_user: ubuntu
  gather_facts: True


  tasks:
   - name: Launch a VM1
     os_server:
        image: "{{ current_image }}"
        name: "{{ current_hostname }}"
        key_name: "{{ key_name }}"
        availability_zone: "{{ availability_zone }}"
        flavor: "{{ current_flavor }}"
        state: present
        wait: yes
        auto_floating_ip: yes
        network: "{{ current_network }}"
        security_groups: "{{ current_security_groups }}"
        meta:
     register: webserver

   - name: Wait for SSH on the Instance
     command: >
        ssh -oBatchMode=yes -oStrictHostKeyChecking=no 
        ubuntu@{{webserver.server.public_v4}} true
     register: result
     retries: 30
     delay: 10 
     ignore_errors: yes
     

   - name: Add ubuntu Instance to Inventory
     add_host: name=webserver groups=webservers
               ansible_ssh_host={{ webserver.server.public_v4 }}
   - ini_file:
        dest: ansible-inventory.ini
        section: webservers
        option: "{{ current_url}}"
        no_extra_spaces: yes
        allow_no_value: yes
        
  
   - ini_file:
         dest: ansible-inventory.ini
         section: IpDNS
         option: "{{ webserver.server.public_v4 }}" 
         value: "{{ current_url }}"
         no_extra_spaces: yes
            