#!/usr/bin/env ansible-playbook

- hosts: webservers
  become: yes

 

- name: Bootstrap Python
  hosts: webservers
  become: true
  remote_user: ubuntu
  gather_facts: true
  roles:
    - roles/bootstrap
  ignore_errors: True  

- name: Install apt packages and docker
  hosts: webservers
  become: true
  remote_user: ubuntu
  gather_facts: true

  tasks:
    - name: Install required packages with apt
      apt:
        name: "{{ bootstrap_packages }}"
        state: present
  roles:
    - roles/docker
    - roles/docker-compose
  ignore_errors: True  
  


  