- name: check DNS
  hosts: DNS
  gather_facts: false
  remote_user: ubuntu
  tasks:
    - name: Add Ansible inventory mappings to /etc/hosts
      become: true
      blockinfile:
        path: /etc/hosts
        block: |
          {% for host in groups['IpDNS'] %}
          {{ host | replace('=', ' ') }}  
          {% endfor %}
    - name: restart Dnsserver
      become: true
      shell: systemctl restart dnsmasq


- name: change Dns of peertube Hosts
  hosts: webservers
  remote_user: ubuntu
  tasks:
    - name: Add Ansible inventory mappings to /etc/hosts
      shell: sudo apt install update

    - name: Add Ansible inventory mappings to /etc/hosts
      shell: sudo apt install resolvconf

    - name: Insert a line at the end of a file.
      become: true
      lineinfile:
        path: /etc/resolvconf/resolv.conf.d/head
        line: nameserver 10.1.30.37
      ignore_errors: True

    - name: restart resolvconf
      become: true
      shell: service resolvconf restart

       
  

  

    