
- name: Run bitflow-collector docker container
  tag: [ docker, collector ]
  docker_container:
    name: "{{ collector.container_name }}"
    image: antongulenko/bitflow-collector
    pid_mode: host
    privileged: yes
    ports:
      - "{{ collector.port }}:{{ collector.port }}"
      - "{{ collector.api_port }}:{{ collector.api_port }}"
    volumes:
      - "{{ collector.data_path }}:{{ collector.data_path_mounted }}"
      - "/etc/hostname:{{ hostname_mounted }}"
    command: >
      {{ collector.extra_args }}
      -api :{{ collector.api_port }}
      -ci {{ collector.interval }} -si {{ collector.interval }}
      -o :{{ collector.port }} -o {{ collector.data_path_mounted }}/{{ collector.file_name }}
