
- name: Install the Bitflow data collector
  hosts:
    - hypervisors
    - vms:!client
  tags: [ collector ]
  vars:
    command_params: >
      {{ collector.extra_command_params }}   
      -exclude 'pcap|net-io/nic'
      -api :{{ collector.collector_api_port }}
      -ci {{ collector.interval }} -si {{ collector.interval }}
      -o :{{ collector.collector_data_output_port }} -o {{ collector.collector_data_mounted }}/data.bin
  tasks:
    - name: Run bitflow-collector docker container
      docker_container:
        name: bitflow-collector
        image: antongulenko/bitflow-collector
        pid_mode: host
        privileged: yes
        ports:
          - "{{ collector.collector_data_output_port }}:{{ collector.collector_data_output_port }}"
          - "{{ collector.collector_api_port }}:{{ collector.collector_api_port }}"
        volumes:
          - "{{ collector.collector_data }}:{{ collector.collector_data_mounted }}"
          - "/etc/hostname:{{ collector.collector_hostname_mounted }}"
        command: "{{ command_params }}"
            
