
- name: Install the Bitflow data collector
  hosts:
    - hypervisors
    - vms:!client
  tags: [ collector ]
  vars:
    command_params: >
      -host {{ injector.host_name }}
      -
  tasks:
    - name: Run bitflow-collector docker container
      docker_container:
        name: bitflow-collector
        image: antongulenko/bitflow-collector
        pid_mode: host
        privileged: yes
        ports:
          - "{{ collector.collector_data_output_port }}:{{ collector.collector_data_output_port }}"
          - "{{ collector.collector_api_port }}:{{ collector.collector_api_port }}"
        volumes:
          - "{{ collector.collector_data }}:{{ collector.collector_data_mounted }}"
          - "/etc/hostname:{{ collector.collector_hostname_mounted }}"
        command: "{{ command_params }}"
            
