
- name: Query OS version
  command: uname -r
  register: version
  changed_when: False

- name: Upgrade linux kernel Step 1
  tags: [ kernel ]
  apt: 
    name: "linux-image-extra-{{ version }}"
    state: present 
    update_cache: yes

- name: Upgrade linux kernel Step 2
  tags: [ kernel ]
  apt: 
    name: "linux-image-extra-virtual"
    state: present 
    update_cache: yes
