
- name: Query OS version
  command: uname -r
  register: version
  changed_when: False

- name: Upgrade linux kernel
  tags: [ kernel ]
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - "linux-image-extra-{{ version }}"
    - "linux-image-extra-virtual"
