
- name: Install the collector and injector
  hosts: localhost
  vars:
    hostname_general: "{{ inventory_hostname }}"
    hostname_service: "local-service@{{ hostname_general }}"
    collector:
      container_name: bitflow-collector
      interval: 500ms
      api_port: 7777
      port: 5010
      file_name: data.bin
      data_path: /tmp/bitflow/data-collector
      data_path_mounted: /bitflow/data-collector
      extra_args: "-proc-children 'stress|vnf_' -tag 'host={{ hostname_service }}'"
    injector:
      container_name: injector-layer-virtual
      hostname: injector-layer-virtual
      api_port: 7778
  tasks:
    - include_tasks: ../../Common/Ansible/bootstrap-python.yml
    - include_tasks: ../../Common/Ansible/bootstrap-docker-tasks.yml
    - include_tasks: ../../Common/Ansible/bitflow-collector-tasks.yml
    - include_tasks: ../../Common/Ansible/injector-tasks.yml

- name: Install the VNF injector
  hosts: localhost
  vars:
    injector:
      container_name: injector-layer-service
      hostname: injector-layer-service
      api_port: 7779
  tasks:
    - include_tasks: ../../Common/Ansible/injector-tasks.yml
