
- name: retrieve swarm manager token
  shell: docker swarm join-token -q manager
  register: swarm_manager_token

- name: retrieve swarm worker token
  shell: docker swarm join-token -q worker
  register: swarm_worker_token
