#!/usr/bin/env ansible-playbook

- name: Preparation
  hosts: all
  tasks:
    - include_tasks: ../../Common/Scripts/query-hostname-task.yml

- name: Check data collector output
  hosts:
    - hypervisors
    - vms
  vars:
    output_check_directory: "{{ collector.data_path }}"
    max_file_age_seconds: 300 # 5 minutes
  tasks:
    - include_tasks: ../../Common/Ansible/check-output-directory-tasks.yml
