#!/usr/bin/env ansible-playbook

- name: Delete collector data
  hosts: all:!sippstress:!etcd:!swarm_manager
  vars:
    injector: "{{ injector_general }}"
  tasks:
    - include_tasks: ../../Common/Ansible/reset-collector-injector-tasks.yml
      become: true
	- include_tasks: ../../Common/Ansible/clean-remote-collector-data-tasks.yml
      become: true
