#!/usr/bin/env ansible-playbook

# The variable 'fetch_dir' must be defined on the command line with ansible-playbook -e fetch_dir=DIR

- name: Preparation
  hosts: all
  tasks:
    - name: Query hostname
      command: cat /etc/hostname
      register: hostname
      changed_when: False

- name: Fetch client statistics data
  hosts: client
  tasks:
    - fetch:
        flat: true
        fail_on_missing: true
        src: "{{ rtmp.client_log_dir }}"
        dest: "{{ fetch_dir }}/{{ inventory_hostname }}/"

- name: Fetch data collector data from remote hosts
  hosts: all
  tasks:
    - fetch:
        flat: true
        fail_on_missing: true
        src: "{{ collector.data_path }}"
        dest: "{{ fetch_dir }}/{{ inventory_hostname }}/"
