
- name: Install general requirements
  hosts: all
  tags: [ boostrap ]
  tasks:
    - include_tasks: ../../Common/Ansible/prepare-docker-tasks.yml

- name: Install the Bitflow data collector
  hosts:
    - hypervisors
    - vms:!client
  tags: [ collector ]
  become: True
  tasks:
    - include_tasks: ../../Common/Ansible/bitflow-collector-tasks.yml

- name: Install the backend video server
  hosts: backend
  tags: [ docker, backend ]
  tasks:
    - name: Run backend video server docker container
      docker_container:
        name: rtmp-server
        image: antongulenko/rtmp-nginx-server
        ports:
          # The container ports are hardcoded because they cannot be configured
          - "{{ backend_http_port }}:8080"
          - "{{ rtmp_port }}:1935"

- name: Install the load balancer
  hosts: load-balancer
  tags: [ docker, load-balancer ]
  tasks:
    - name: Run load balancer docker container
      docker_container:
        name: rtmp-balancer
        image: antongulenko/rtmp-haproxy-balancer
        ports:
          - "{{ rtmp_port }}:{{ rtmp_port }}"
          - "{{ balancer_stats_port }}:{{ balancer_stats_port }}"
        env:
          RTMP_PORT: "{{ rtmp_port }}"
          STATS_PORT: "{{ balancer_stats_port }}"
          RTMP_SERVERS: "{{ groups['backend'] | map('extract', hostvars, ['ansible_host']) | join(' ') }}"

- name: Install the load generation client
  hosts: client
  tags: [ docker, client ]
  vars:
    data_directory: /opt/bitflow/rtmp-client
    data_directory_mounted: /rtmp-client-data
  tasks:
    - name: Create local service quality data directory
      file:
        path: "{{ data_directory }}"
        state: directory
    - name: Run client docker container
      docker_container:
        name: rtmp-client-{{ item }}
        image: antongulenko/rtmp-client
        volumes:
          - "{{ data_directory }}:{{ data_directory_mounted }}"
        env:
          MRL_PORT: "{{ rtmp_port }}"
          MRL_PATH: "{{ rtmp_path }}"
          LOOP: -1
          PARALLEL: 1
          MRL_LOG: "{{ data_directory_mounted }}/{{ rtmp_log_file }}-{{ item }}"
          MRL_SERVER: "{{ groups['load-balancer'] | map('extract', hostvars, ['ansible_host']) | join(' ') }}"
      with_sequence: count={{ clients_per_host }}
