
- name: Install prerequisites for managing docker over Ansible
  hosts: all
  tags: [ bootstrap ]
  become: True
  tasks:
    - name: Install pip
      package:
        name: python-pip
        state: present
    - name: Install docker-py
      pip:
        name: docker-py
        state: present

- name: Install the Bitflow data collector
  hosts:
    - hypervisors
    - vms:!client
  tags: [ collector ]
  become: True
  tasks:
    - name: Create local collector data directory
      file:
        path: "{{ collector_data }}"
        state: directory
    - name: Run bitflow-collector docker container
      docker_container:
        name: bitflow-collector
        image: antongulenko/bitflow-collector
        pid_mode: host
        privileged: yes
        ports:
          - "{{ collector_port }}:{{ collector_port }}"
          - "{{ collector_api_port }}:{{ collector_api_port }}"
        volumes:
          - "{{ collector_data }}:{{ collector_data_mounted }}"
        command: |
            {{ collector.extra_args }}
            -api :{{ collector_api_port }}
            -ci {{ collector_interval }} -si {{ collector_interval }}
            -o :{{ collector_port }} -o {{ collector_data_mounted }}/{{ collector_file_name }}

- name: Install the backend video server
  hosts: backend
  tags: [ docker, backend ]
  tasks:
    - name: Run backend video server docker container
      docker_container:
        name: rtmp-server
        image: antongulenko/rtmp-nginx-server
        ports:
          - 8080:8080
          - 1935:1935

- name: Install the load balancer
  hosts: load-balancer
  tags: [ docker, load-balancer ]
  tasks:
    - name: Run load balancer docker container
      docker_container:
        name: rtmp-balancer
        image: antongulenko/rtmp-haproxy-balancer
        ports:
          - 1935:1935
        command: ?? # TODO

- name: Install the load generation client
  hosts: client
  tags: [ docker, client ]
  vars:
    data_directory: /opt/bitflow/rtmp-client
    data_directory_mounted: /rtmp-client-data
  tasks:
    - name: Create local service quality data directory
      file:
        path: "{{ data_directory }}"
        state: directory
    - name: Run client docker container
      docker_container:
        name: rtmp-client
        image: antongulenko/rtmp-client
        volumes:
          - "{{ data_directory }}:{{ data_directory_mounted }}"
        command: ?? # TODO
