#!/usr/bin/env ansible-playbook

- name: Install Python
  tags: [ bootstrap ]
  hosts: all
  gather_facts: false
  tasks:
    - include_tasks: ../../Common/Ansible/bootstrap-python.yml
      become: true

- name: Preparation
  hosts: all
  tasks:
    - name: Query hostname
      command: cat /etc/hostname
      register: hostname
      changed_when: False
    - include_tasks: ../../Common/Ansible/bootstrap-docker-tasks.yml
      become: true

- name: Install the Bitflow collector and injector
  hosts:
    - hypervisors
    - vms:!client
  tasks:
    - include_tasks: ../../Common/Ansible/bitflow-collector-tasks.yml
      tags: [ docker, collector ]
      become: true
    - include_tasks: ../../Common/Ansible/injector-tasks.yml
      tags: [ docker, injector ]
      become: true

