#!/usr/bin/env ansible-playbook

- name: Install the load generation client
  hosts: client
  tags: [ docker, client ]
  tasks:
    - name: Create local client targets directories
      become: true
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ rtmp.client_targets_dir }}"
    - name: Create local client directories
      become: true
      file:
        path: "{{ rtmp.client_log_dir }}/{{ rtmp.client_log_dir_prefix }}-{{ item }}"
        state: directory
      with_sequence: count={{ rtmp_clients_per_host }}
    - name: Create default load generation targets file
      become: true
      copy:
        dest: "{{ rtmp.client_targets_dir }}/{{ item }}.txt"
        force: false
        content: |
          CMD sleep 3
#{% for host in groups['load-balancer'] %}
#rtmp://{{ hostvars[host]['private_ip'] }}:{{ rtmp.port }}{{ rtmp.default_request_path }}
#{% endfor %}
      with_sequence: count={{ rtmp_clients_per_host }}
    - name: Delete excess load generation targets files
      become: true
      shell: |
        # Delete files that are not used (in case of scaling down the number of clients)
        expected_files=$(for i in $(seq {{ rtmp_clients_per_host }}); do echo "-o -name $i.txt"; done)
        NUM=$(find "{{ rtmp.client_targets_dir }}" -type f -a -not \( -false $expected_files \) -delete -print | wc -l)
        test "$NUM" -gt 0 && exit 66 || exit 0
      args:
        executable: /bin/bash
      register: delete_excess_targets
      changed_when: "delete_excess_targets.rc == 66"
      failed_when: "delete_excess_targets.rc != 66 and delete_excess_targets.rc != 0"
    - name: Run client docker container
      become: true
      docker_container:
        name: rtmp-client-{{ item }}
        image: antongulenko/rtmp-client
        pull: true
        volumes:
          - "{{ rtmp.client_log_dir }}:{{ rtmp.client_log_dir_mounted }}"
          - "{{ rtmp.client_targets_dir }}:{{ rtmp.client_targets_dir_mounted }}"
        env:
          MRL_LOG_DIR: "{{ rtmp.client_log_dir_mounted }}/{{ rtmp.client_log_dir_prefix }}-{{ item }}"
          LOOP: -1
          MRL_BATCH_FILE: "{{ rtmp.client_targets_dir_mounted }}/{{ item }}.txt"
          MRL_BATCH_INDEX_OFFSET: -1 # Random offset for every client
      with_sequence: count={{ rtmp_clients_per_host }}
    - name: Query names of client containers
      shell: |
        mapfile -t CONTAINERS <<< $(docker ps --no-trunc --format '{% raw %}{{.Names}}{% endraw %}' --filter 'Name=rtmp-client-*')
        for name in ${CONTAINERS[*]}; do
          client_num="${name:12}" # 12 is the length of 'rtmp-client-' (the container name prefix), which is stripped to obtain the number in the end
          # Output the IDs of all containers with numbers outside of the configured range
          test "$client_num" -lt 0 -o "$client_num" -gt {{ rtmp_clients_per_host}} && echo "$name" || continue
        done
      args:
        executable: /bin/bash
      register: client_containers
      changed_when: false
    - name: Kill client containers
      docker_container:
        name: "{{ item }}"
        state: absent
      with_items: "{{ client_containers.stdout_lines }}"
