#!/usr/bin/env ansible-playbook

- name: Install Python
  tags: [ bootstrap ]
  hosts: vms
  gather_facts: false
  tasks:
    - include_tasks: ../../Common/Ansible/bootstrap-python.yml
      become: true

- name: Install Docker
  tags: [ bootstrap ]
  hosts: vms
  tasks:
    - include_tasks: ../../Common/Ansible/install_docker.yml
      become: true
    - include_tasks: ../../Common/Ansible/bootstrap-docker-tasks.yml
      become: true

- name: Install the Bitflow collector and injector
  tags: [ injector, collector ]
  hosts: all
    #- wally193
  tasks:
    - include_tasks: ../../Common/Ansible/bitflow-collector-tasks.yml
      tags: [ docker, collector ]
      become: true
    - include_tasks: ../../Common/Ansible/injector-tasks.yml
      tags: [ docker, injector ]
      become: true
    - include_tasks: ../../Common/Ansible/ebpf-agent-tasks.yml
      tags: [ docker, ebpf-agent ]
      become: true
