#!/usr/bin/env ansible-playbook

- include: ../../Common/Scripts/clean-remote-collector-data.yml

- name: Delete client statistics data
  hosts: client
  tasks:
    - command: rm -rf "{{ rtmp.client_log_dir }}/*"

