#!/usr/bin/env ansible-playbook

- name: Preparation
  hosts: all
  tasks:
    - name: Query hostname
      command: cat /etc/hostname
      register: hostname
      changed_when: False

- name: Unset collector tags, stop file outputs, stop all running anomalies on VM and Host layer
  hosts:
    - hypervisors
    - vms:!client
  tasks:
    - uri:
        url: "{{ item }}"
        method: DELETE
      with_items:
        - "http://0.0.0.0:{{ collector.api_port }}/api/anomalies/"
        - "http://0.0.0.0:{{ collector.api_port }}/api/file_output/"
        - "http://0.0.0.0:{{ injector.api_port }}/api/anomalies/"

