#!/usr/bin/env ansible-playbook

# The variable 'fetch_dir' must be defined on the command line with ansible-playbook -e fetch_dir=DIR

- name: Preparation
  hosts: all
  tasks:
    - name: Query hostname
      command: cat /etc/hostname
      register: hostname
      changed_when: False

- name: Restart all client containers
  hosts: client
  tasks:
    - become: true
      docker_container:
        name: rtmp-client-{{ item }}
        state: started
        recreate: true
      with_sequence: count={{ rtmp_clients_per_host }}
